name: Code Quality

on:
  - push
  - pull_request

permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  quality:
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_portal-event-ingest
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-func-ci
      dotnet-project: XtremeIdiots.Portal.Events.Ingest.App.V1
      dotnet-version: 9.0.x
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
